# Generated by Django 4.1.4 on 2024-03-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reflio_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='affiliate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='referral',
            table=None,
        ),
    ]
