# Generated by Django 4.1.4 on 2024-05-27 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reflio_django_app', '0006_alter_campaign_campaign_id_alter_campaign_user'),
    ]

    operations = [
        # Drop the existing index if it exists
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS reflio_django_app_campaign_campaign_id_idx;",
            reverse_sql="CREATE INDEX reflio_django_app_campaign_campaign_id_idx ON reflio_django_app_campaign (campaign_id varchar_pattern_ops);"
        ),
        # Alter the user field back to ForeignKey
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
