# Generated by Django 4.1.4 on 2024-05-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reflio_django_app', '0008_alter_affiliate_affiliate_id_alter_member_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='team_id',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflio_django_app.team'),
            preserve_default=False,
        ),
    ]
